#! /bin/bash
FROM=$1
MESSAGE=$2
URL=https://telenormobil.no/ums/smapi/input?sender=$FROM&password=$PASSWORD&recipients=$FROM&sId=1000000000&content=$MESSAGE
echo Number is: $FROM
echo Message is: $MESSAGE
